pipeline{
    agent {
        node {
          label 'master'
        }

      }
    stages{
        stage("Get Source Code"){
            steps{
                //checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/dcarbajosa/somefun.git']]])
            }
        }
        stage('Deploy Apps') {
            parallel {
                stage('Deploy App1') {
                    steps {
                        sh "docker build -f infra/app1/Dockerfile -t dc/nginx-hw1:latest ."
                        sh "docker run -i -t -d --name hw1 -p 8085:80 dc/nginx-hw1:latest"
                    }
                }
                stage('Deploy App2') {
                    steps {
                        sh "docker build -f infra/app2/Dockerfile -t dc/nginx-hw2:latest ."
                        sh "docker run -i -t -d --name hw2 -p 8086:80 dc/nginx-hw2:latest"

                    }
                }
            }
        }
        stage('Clean up') {
            steps {
                input "Exploratory Test"
            }
            post {
                always {

                    sh "docker stop hw1"
                    sh "docker rm hw1"
                    sh "docker rmi dc/nginx-hw1:latest"
                    sh "docker stop hw2"
                    sh "docker rm hw2"
                    sh "docker rmi dc/nginx-hw2:latest"
                    deleteDir()
                }
            }
        }
    }
}