#!groovy
@Library("edyga-jenkins-shared-libraries") _
pipeline{
    agent {
        node {
            label 'master'
        }
    }
     options {
        buildDiscarder(logRotator(numToKeepStr:'1'))
        disableConcurrentBuilds()
    }
    stages{
        stage('Deploy Apps') {
            parallel {
                stage('Deploy App1') {
                    steps {
                        deployDockerApp (
                            dockerFileLocation: "infra/app1/Dockerfile",
                            dockerImageName: "dc/nginx-hw1:latest",
                            appContainerName: "hw1",
                            portMapping: "8085:80"
                        )
                    }
                }
                stage('Deploy App2') {
                    steps {
                        deployDockerApp(
                            dockerFileLocation: "infra/app2/Dockerfile",
                            dockerImageName: "dc/nginx-hw2:latest",
                            appContainerName: "hw2",
                            portMapping: "8086:80"
                        )
                    }
                }
            }
        }
        stage('Clean up') {
            input {
                message "Exploratory Test"
            }
            post {
                always {
                    deleteDockerApp(
                        dockerImageName: "dc/nginx-hw1:latest",
                        appContainerName: "hw1"
                    )
                    deleteDockerApp(
                        dockerImageName: "dc/nginx-hw2:latest",
                        appContainerName: "hw2"
                    )
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}